/* Calculate the final order price
A retail store needs to calculate the total cost of items in a customer's cart. A customer cart is an array of
objects with unit price and quantity. Implement an arrow function to calculate the total cost of items, based on
the unit price and quantity of each item. */

let cart = {
    soap : 10 ,
    toothpase : 20,
    sugar : 45,
    tea : 10
};

 const calculateTotalCost = (cart) => {
    let totalCost = 0;
 for (let i = 0; i < cart.length; i++){
    const {unitPrice,quantiyu = 
 }
};